# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Component' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Component
    pod 'SubModule1', :path => './SubModule1'
    pod 'SubModule2', :path => './SubModule2'
    pod 'Matrix', :path => './Matrix'

end
